name: bannertest
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_admob: 
    git:
      url: git@github.com:flutter/flutterfire_temporary.git
      ref: master
      path: packages/firebase_admob
  smads:
    git:
      url: https://github.com/SuaMusica/flutter_plugins.git
      path: packages/ads/
  provider: ^4.3.2+2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

